# Generated by Django 4.0.6 on 2025-01-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
