# Generated by Django 4.2.18 on 2025-01-26 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cab_users', '0005_booking_timestamp_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
