# Generated by Django 4.2.18 on 2025-02-09 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cab_users', '0007_cab_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='total_trip',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='aadhaar_doc',
            field=models.FileField(null=True, upload_to='aadhaar_docs/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='aadhaar_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_doc',
            field=models.FileField(null=True, upload_to='license_docs/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driverrating',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_booking', to='cab_users.booking'),
        ),
    ]
