# Generated by Django 4.1.7 on 2025-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_users', '0008_driver_total_trip_alter_driver_aadhaar_doc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cab',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='final_fare',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='buy_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(default='hellp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_number',
            field=models.CharField(default=76543210987, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='drop_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bidding_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(choices=[('one_way', 'One Way'), ('round', 'Round Trip')], max_length=20),
        ),
    ]
